### ISSUE TITLE
About evaluation during training

### ISSUE THREAD

**Issue by HaolinLiu97** [princeton-computational-imaging/Diffusion-SDF#11]
Hi, thank you for your great work! I am wondering why only a train loader is used during the training. Without evaluation for each epoch, it is hard to decide which epoch will be the best. Will the evaluation be added in the future?

**Comment by gene-chou** [comment]
This can be done by changing the `ModelCheckpoint` callback in `train.py`. Change `save_top_k` to greater than 1, and add `monitor="sdf"`. For example: 
`callback = ModelCheckpoint(dirpath=args.exp_dir, filename='{epoch}', save_top_k=3, save_last=False, every_n_epochs=specs["log_freq"], monitor="sdf")`
