### ISSUE TITLE
Question about inference time

### ISSUE THREAD

**Issue by AlbertoRemus** [princeton-computational-imaging/Diffusion-SDF#12]
Hi! really nice and elegant work!

I would like to ask what's the inference time of the reported approach as range/order of magnitude

Thanks in advance

**Comment by gene-chou** [comment]
I'm not sure what you mean by order of magnitude, but on an NVIDIA A100 one sampling batch takes 10-15 seconds wall time.

**Comment by AlbertoRemus** [comment]
Thanks for your reply!
