### ISSUE TITLE
pretrained weights release

### ISSUE THREAD

**Issue by ShengyuH** [princeton-computational-imaging/Diffusion-SDF#13]
hi,

Congrats on having this paper accepted to ICCV, do you have an updated plan regarding pretrained weights release? 

Best,
Shengyu

**Comment by gene-chou** [comment]
Hey Shengyu, we refactored the code so the names and structure of the weights are different from the pretrained. We plan to retrain the models when we have the computing resources. Closing comment for now but will reopen when we're done.

**Comment by ShengyuH** [comment]
okay sure, do you have a timeline for that? let's say before ICCV conference? or?

**Comment by dqj5182** [comment]
Do you plan to release the weights anytime soon?

**Comment by GG-Bonds** [comment]
+1
