### ISSUE TITLE
Technical question about point cloud condition

### ISSUE THREAD

**Issue by jbHu67** [princeton-computational-imaging/Diffusion-SDF#14]
I have a technical question: When using PointNet for feature extraction on partial point clouds to use them as conditions, is your approach to directly extract features using a pre-trained model, or to train PointNet simultaneously with the main diffusion network?

**Comment by gene-chou** [comment]
We trained from scratch and simultaneously with the diffusion network.

**Comment by jbHu67** [comment]
> We trained from scratch and simultaneously with the diffusion network.

Ok, thanks for your reply.
