### ISSUE TITLE
Data Preprocessing

### ISSUE THREAD

**Issue by cuicanyu** [princeton-computational-imaging/Diffusion-SDF#15]
hi,thank you to release this nice work! I want follow this do some further experiments, could you release data preprocessing code?

**Comment by kenchen3000** [comment]
+1, seems like we need the full data for couch to successfully run the training. the repository only have one couch? I think the preprocessing code is needed to generate the full dataset before training? thanks!

**Comment by gene-chou** [comment]
Please check #4 and #8
