### ISSUE TITLE
One Quesiton about Data Preprocessing

### ISSUE THREAD

**Issue by cnexah** [princeton-computational-imaging/Diffusion-SDF#16]
Hi, thank you for your great work!
I have a question about the acronym data:
In paper, you keep the categories with at least 20 objects, and obtain 106 classes in the end.
However, when I process the data, I finally get 119 classes. Do you have other filter strategies？
The following is the classes I obtained and the number of objects:
Horse 22
SideChair 76
Loveseat 24
Airplane 33
Vase 172
Gun 55
Cabinet 154
PottedPlant 101
Sideboard 77
Cup 62
Spoon 22
Armoire 98
SingleBed 32
FloorLamp 135
WallLamp 65
OfficeChair 119
Chair 310
Sink 41
Monitor 133
ChestOfDrawers 145
Mug 101
Picture 73
Laptop 183
Hammer 26
PersonStanding 57
Guitar 66
Chaise 39
TV 238
AccentTable 75
Mirror 46
AccentChair 54
Table 90
Bottle 44
MediaPlayer 63
Piano 39
DeskLamp 99
GameTable 25
Book 90
Telephone 35
Barstool 71
Dresser 218
ToyFigure 81
WallArt 58
Fireplace 35
Knife 58
Desktop 75
Speaker 71
Couch 400
Desk 196
StandingClock 28
QueenBed 102
LampPost 25
CellPhone 138
Keyboard 30
RoundTable 32
TableLamp 57
Calculator 37
NintendoDS 21
OfficeSideChair 44
EndTable 92
CoffeeTable 80
Bench 89
Painting 53
Pillow 28
CeilingLamp 60
WineBottle 28
Refrigerator 65
Stapler 38
DrinkingUtensil 30
Bowl 83
FileCabinet 20
LoftBed 25
FoodItem 66
Pencil 82
Plant 76
Recliner 29
Toilet 42
4Shelves 28
TrashBin 120
TissueBox 24
Rug 54
DiningTable 91
Camera 65
Basket 21
WallClock 46
PaperBox 33
PianoKeyboard 33
Curtain 57
Pizza 24
Candle 51
Poster 39
Headphones 24
Printer 44
USBStick 31
Books 24
Pan 36
WallUnit 48
Pen 27
DresserWithMirror 22
WineGlass 20
CeilingFan 20
ComputerMouse 20
Plate 36
LightSwitch 40
ToiletPaper 34
SodaCan 45
Oven 36
Sword 44
Microwave 26
TableClock 38
Stool 27
CerealBox 27
Mattress 21
PictureFrame 29
Nightstand 57
Lamp 30
TvStand 32
Fork 22
Room 20

**Comment by cnexah** [comment]
I see, there are some categories with different scales. 
When I remove the replicates, the number is correct!

**Comment by saligia-ira** [comment]
I wanna know how to process the data , just follow the paper of acronym ?
