### ISSUE TITLE
Data preprocessing for grid data

### ISSUE THREAD

**Issue by liang3588** [princeton-computational-imaging/Diffusion-SDF#17]
Could you please explain what data/grid_data/acronym/Couch/37cfcafe606611d81246538126da07a8/grid_gt.csv denotes? For example, "0.195652,-0.413043,-0.00724638,0.255061" in the first line, (0.195652,-0.413043,-0.00724638) is the coordinate of a sample point, and 0.255061 is its SDF value? Am I right?

**Comment by gene-chou** [comment]
correct, for all the files, each line represents a coordinate (x,y,z) and its corresponding SDF value
