### ISSUE TITLE
The effect of VAE

### ISSUE THREAD

**Issue by CNGaoWenbo** [princeton-computational-imaging/Diffusion-SDF#19]
Thank you for your work. I am confused about the effect of VAE here. Is VAE used as a speeder for the diffusion model? With the VAE, the diffusion model can learn the latent space z instead of the raw point clouds. is that correct? So ignoring the great computation cost, the VAE can be abandoned.

**Comment by gene-chou** [comment]
The VAE also helps with interpolation and smoother training of the diffusion model. Directly learning the point clouds or the triplanes would likely require additional regularization loss functions and diffusion architectures.
