### ISSUE TITLE
num_modulations referenced but not used

### ISSUE THREAD

**Issue by gattia** [princeton-computational-imaging/Diffusion-SDF#2]
Hi, 

It seems like there could be something that was omitted or skipped - the `num_modulations` is defined in an if/else statement for the sdf_decoder but it's never used. 

This is presumably to do with it being the same as the `hidden_dim` in the `latent_in == True` case - or the `mod_net` that is commented out. Not sure of the effects (yet) but raising the issue here in case it is useful/helpful. 

see here: 

https://github.com/princeton-computational-imaging/Diffusion-SDF/blob/64dc177a43517d17077e6ff7d16160cf64e78255/train_sdf/models/archs/sdf_decoder.py#L74-L84

**Comment by gene-chou** [comment]
This was back when we were experimenting with the sdf decoder. We tried auto-decoders ([DeepSDF](https://arxiv.org/abs/1901.05103)) as well as mapping latent vectors to linearly shift the base network ([pi-GAN](https://arxiv.org/abs/2012.00926)). The decoder should work fine with the currently provided specs, but we'll clean it up sometime in the future.

**Comment by gattia** [comment]
Thanks for the explanation.
