### ISSUE TITLE
The data used for training the SDF-VAE and combined model when using the YCB dataset

### ISSUE THREAD

**Issue by EAST-J** [princeton-computational-imaging/Diffusion-SDF#23]
Hi, thanks for your great work. I'm curious, when you used YCB for conditioning, did you also utilize other datasets such as Acronym to train the SDF-VAE, or just use the YCB datasets for all three training stages?

**Comment by gene-chou** [comment]
We used both acronym and the YCB dataset for all training stages. I would also recommend finetuning on YCB on any stage that doesn't seem to have good performance on YCB.
