### ISSUE TITLE
Question about the number of classes

### ISSUE THREAD

**Issue by pigtigger** [princeton-computational-imaging/Diffusion-SDF#3]
Hi,
I notice that Diffusion-SDF trains a VAE on multiple classes in the paper, but I only find the 'couch' class in this repo. Could I simply train a multi-class VAE using your code? I am wondering if you could provide more details about multi-class training.
Thanks

**Comment by gene-chou** [comment]
Create a `.json` file with the classes and items you want, for example
```
"acronym": {
        "Couch": [
            "37cfcafe606611d81246538126da07a8",
            "fd124209f0bc1222f34e56d1d9ad8c65", ...],
        "Airplane":[
            "655dc5a5376e9c8152c3271e911ffe19",
            "724af978f659993e890824251c0961f3",...]
}
```
Then use this as the train/test split in the config files and place the corresponding data in the `data` folder.

**Comment by pigtigger** [comment]
Thanks for your help. Sorry to bother you again, but could you share your multi-class split file with me?

**Comment by gene-chou** [comment]
Uploaded to `train_sdf/data/splits`
