### ISSUE TITLE
Data processing code

### ISSUE THREAD

**Issue by linjing7** [princeton-computational-imaging/Diffusion-SDF#8]
Hi, thanks for your excellent work. I wonder if could you please provide the data processing code.  So that we can train on our own dataset.

**Comment by gene-chou** [comment]
We recommend checking these two repos for detailed instructions:
https://github.com/facebookresearch/DeepSDF
https://github.com/marian42/mesh_to_sdf

Then, create sample points both uniformly and close to the surface.
