### ISSUE TITLE
No reconstruction loss for VAE

### ISSUE THREAD

**Issue by space1panda** [princeton-computational-imaging/Diffusion-SDF#9]
Hello, 

It seems that you resigned from using reconstruction loss of planar features (it's commented out in BetaVAE object). Could you please elaborate, why we can expect the model to learn sensible latent space without minimizing reconstruction objective? Does SDF objective somehow compensate the reconstruction? Thanks for the answer

**Comment by gene-chou** [comment]
Yep, we do not use the reconstruction loss. The plane/shape features do not necessarily need to be the same before encoding and after decoding, as long as the decoded features contain sufficient information for reconstructing the SDF.
